version: '3.8'
services:
  # webapp config
  web:
    container_name: express_app
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.prod
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 3000:3000
    networks:
      express_network:
  # postgres config
  db:
    container_name: pg_database
    restart: always
    image: postgres:latest
    environment:
      - POSTGRES_USER=restuwahyu13
      - POSTGRES_PASSWORD=restuwahyu13
      - POSTGRES_DB=payment
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      express_network:

volumes:
  pgdata:

networks:
  express_network:
